# Generated by Django 4.0.1 on 2022-10-22 14:38

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='properties_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('poster', models.ImageField(blank=True, upload_to=mainapp.models.property_poster_path)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('property_type', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('price', models.IntegerField(blank=True)),
                ('locality', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('pin_code', models.CharField(blank=True, max_length=255)),
                ('other_amenities', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='properties_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=mainapp.models.property_images_path)),
                ('img_caption', models.CharField(blank=True, max_length=255)),
                ('pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties_img', to='mainapp.properties_detail')),
            ],
        ),
    ]
