# Generated by Django 4.0.1 on 2022-10-22 14:40

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties_detail',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.property_poster_path),
        ),
    ]
