# Generated by Django 4.0.1 on 2022-10-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_properties_detail_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='intrested_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone_no', models.IntegerField(blank=True)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.properties_detail')),
            ],
        ),
    ]
