# Generated by Django 4.0.1 on 2022-10-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_intrested_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties_detail',
            name='status',
            field=models.CharField(blank=True, choices=[('uc', 'Under Construction'), ('js', 'Just Launched'), ('rm', 'Ready to Move'), ('so', 'Sold Out')], max_length=255),
        ),
    ]
