# Generated by Django 4.0.1 on 2022-10-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_properties_detail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties_detail',
            name='district',
            field=models.CharField(blank=True, choices=[('dehradun', 'Dehradun'), ('haridwar', 'Haridwar'), ('chamoli', 'Chamoli'), ('rudraprayag', 'Rudraprayag'), ('tehri', 'Tehri'), ('uttarkashi', 'Uttarkashi'), ('pauri', 'Pauri'), ('almora', 'Almora'), ('nanital', 'Nanital'), ('pithoragarh', 'Pithoragarh'), ('usnagar', 'Udham Singh Nagar'), ('bageshwar', 'Bageshwar'), ('champawat', 'Champawat')], max_length=255),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='status',
            field=models.CharField(blank=True, choices=[('uc', 'Under Construction'), ('js', 'Just Launched'), ('rm', 'Ready to Move'), ('so', 'Sold Out')], default='rm', max_length=255),
        ),
    ]
