# Generated by Django 4.0.1 on 2022-10-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_properties_detail_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties_detail',
            name='property_type',
            field=models.CharField(blank=True, choices=[('std', 'Studio'), ('1b', '1 bhk'), ('2b', '2bhk'), ('3b', '3bhk')], max_length=255),
        ),
    ]
