# Generated by Django 4.0.1 on 2022-10-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_properties_detail_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_detail',
            name='owner_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='properties_detail',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='properties_detail',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
