# Generated by Django 4.0.1 on 2022-11-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_properties_detail_owner_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_detail',
            name='commercial_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties_detail',
            name='our_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties_detail',
            name='owner_discription',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='properties_detail',
            name='residential_property',
            field=models.BooleanField(default=False),
        ),
    ]
