# Generated by Django 4.0.1 on 2022-11-26 05:29

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_properties_detail_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties_detail',
            name='poster',
            field=models.ImageField(null=True, upload_to=mainapp.models.property_poster_path),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
