# Generated by Django 4.0.1 on 2022-12-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_detail',
            name='featured_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties_detail',
            name='numbered_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties_detail',
            name='property_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intrested_user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='other_amenities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='our_property',
            field=models.BooleanField(default=True),
        ),
    ]
