# Generated by Django 4.0.1 on 2022-12-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_properties_detail_featured_property_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties_detail',
            old_name='locality',
            new_name='dimensions',
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='district',
            field=models.CharField(blank=True, choices=[('Dehradun', 'Dehradun'), ('Haridwar', 'Haridwar'), ('Chamoli', 'Chamoli'), ('Rudraprayag', 'Rudraprayag'), ('Tehri', 'Tehri'), ('Uttarkashi', 'Uttarkashi'), ('Pauri', 'Pauri'), ('Almora', 'Almora'), ('Nanital', 'Nanital'), ('Pithoragarh', 'Pithoragarh'), ('Udham Singh Nagar', 'Udham Singh Nagar'), ('Bageshwar', 'Bageshwar'), ('Champawat', 'Champawat')], max_length=255),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='property_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
