# Generated by Django 4.0.1 on 2022-12-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_rename_locality_properties_detail_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties_detail',
            name='resdential_property_type',
        ),
        migrations.AddField(
            model_name='properties_detail',
            name='residential_property_type',
            field=models.CharField(blank=True, choices=[('Studio', 'Studio'), ('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('House', 'House'), ('Villa', 'Villa'), ('Plots', 'Plots')], max_length=255),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='commercial_property_type',
            field=models.CharField(blank=True, choices=[('Office Space', 'Office Space'), ('Food Court', 'Food Court'), ('Shopping Complex', 'Shopping Complex'), ('Retail Shops', 'Retail Shops'), ('Plots', 'Plots'), ('Hotel', 'Hotel')], max_length=255),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='status',
            field=models.CharField(blank=True, choices=[('Under Construction', 'Under Construction'), ('Just Launched', 'Just Launched'), ('Ready to Move', 'Ready to Move'), ('Sold Out', 'Sold Out')], default='rm', max_length=255),
        ),
    ]
