# Generated by Django 4.0.1 on 2022-12-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_properties_detail_resdential_property_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties_detail',
            old_name='dimensions',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='status',
            field=models.CharField(blank=True, choices=[('Under Construction', 'Under Construction'), ('Just Launched', 'Just Launched'), ('Ready to Move', 'Ready to Move'), ('Sold Out', 'Sold Out')], default='Ready to Move', max_length=255),
        ),
    ]
