# Generated by Django 4.0.1 on 2022-12-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_other_amenities_properties_detail_other_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_detail',
            name='out_property_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='commercial_property_type',
            field=models.CharField(blank=True, choices=[('Office Space', 'Office Space'), ('Food Court', 'Food Court'), ('Shopping Complex', 'Shopping Complex'), ('Retail Shops', 'Retail Shops'), ('Plots', 'Plots'), ('Hotel', 'Hotel')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='district',
            field=models.CharField(blank=True, choices=[('Dehradun', 'Dehradun'), ('Haridwar', 'Haridwar'), ('Chamoli', 'Chamoli'), ('Rudraprayag', 'Rudraprayag'), ('Tehri', 'Tehri'), ('Uttarkashi', 'Uttarkashi'), ('Pauri', 'Pauri'), ('Almora', 'Almora'), ('Nanital', 'Nanital'), ('Pithoragarh', 'Pithoragarh'), ('Udham Singh Nagar', 'Udham Singh Nagar'), ('Bageshwar', 'Bageshwar'), ('Champawat', 'Champawat')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='owner_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='owner_discription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='pin_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='residential_property_type',
            field=models.CharField(blank=True, choices=[('Studio', 'Studio'), ('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('House', 'House'), ('Villa', 'Villa'), ('Plots', 'Plots')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='properties_detail',
            name='status',
            field=models.CharField(blank=True, choices=[('Under Construction', 'Under Construction'), ('Just Launched', 'Just Launched'), ('Ready to Move', 'Ready to Move'), ('Sold Out', 'Sold Out')], default='Ready to Move', max_length=255, null=True),
        ),
    ]
