# Generated by Django 4.0.1 on 2022-12-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_properties_detail_bathroom_properties_detail_bedroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
    ]
