# Generated by Django 4.0.1 on 2022-12-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_feeback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feeback',
            new_name='feedback',
        ),
    ]
