# Generated by Django 4.0.1 on 2022-12-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_rename_feeback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties_detail',
            name='price_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='properties_detail',
            name='price_to',
            field=models.IntegerField(null=True),
        ),
    ]
